# Generated by Django 4.2.4 on 2025-09-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Site Logo', max_length=100)),
                ('logo_image', models.ImageField(help_text='Upload site logo', upload_to='logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this logo currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['-created_at'],
            },
        ),
    ]
