# Generated by Django 4.2.4 on 2025-09-26 10:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Banner', max_length=100)),
                ('banner_image', models.ImageField(help_text='Upload banner image', upload_to='banners/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this banner currently active?')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (lower number = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
