# Generated by Django 4.2.4 on 2025-09-29 12:47

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_emailtemplate_emailsettings_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='One of the biggest online shopping platform in Bangladesh.', help_text='Company description for footer')),
                ('copyright', models.CharField(default='© 2024 GreatKart. All rights reserved', help_text='Copyright text for footer', max_length=200)),
                ('email', models.EmailField(default='info@greatkart.com', help_text='Contact email for footer', max_length=254)),
                ('phone', models.CharField(default='+880-123-456-789', help_text='Contact phone for footer', max_length=20)),
                ('about_us', models.TextField(default='GreatKart is your one-stop destination for quality products at affordable prices. We are committed to providing excellent customer service and fast delivery across Bangladesh.', help_text='About us description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this footer setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='Social media platform name (e.g., Facebook, Instagram)', max_length=50)),
                ('url', models.URLField(help_text='Social media profile URL')),
                ('icon', models.CharField(default='fab fa-link', help_text='FontAwesome icon class (e.g., fab fa-facebook-f)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this social link is active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('footer_setting', models.ForeignKey(help_text='Footer setting this social link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='settings.footersettings')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order', 'platform'],
            },
        ),
    ]
