# Generated by Django 4.2.4 on 2025-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_footersettings_socialmedialink'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='mission',
            field=models.TextField(default='To provide the best online shopping experience with quality products, competitive prices, and excellent customer service.', help_text='Company mission statement'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='vision',
            field=models.TextField(default="To become Bangladesh's leading e-commerce platform, connecting customers with quality products and services.", help_text='Company vision statement'),
        ),
    ]
