# Generated by Django 4.2.4 on 2025-09-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_footersettings_mission_footersettings_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='business_hours',
            field=models.TextField(default='Monday - Friday: 9:00 AM - 6:00 PM\nSaturday: 10:00 AM - 4:00 PM\nSunday: Closed', help_text='Business hours information'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='quick_response',
            field=models.TextField(default='We typically respond to all inquiries within 24 hours during business days.', help_text='Quick response information'),
        ),
    ]
