# Generated by Django 4.2.4 on 2025-09-20 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('user', 'full_name', 'phone_number', 'address_line_1', 'city', 'country')},
        ),
    ]
