# Generated by Django 4.2.4 on 2025-09-16 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_productreview_reviewvote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for guest users', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the cart was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the cart was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this cart is still active')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this cart expires (for guest users)', null=True)),
                ('total_items', models.PositiveIntegerField(default=0, help_text='Total number of items in cart')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before taxes and shipping', max_digits=10)),
                ('user', models.ForeignKey(blank=True, help_text='User who owns this cart (null for guest users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Wishlist', help_text='Name of the wishlist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the wishlist was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the wishlist was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this wishlist is still active')),
                ('user', models.ForeignKey(help_text='User who owns this wishlist', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of this item in cart', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit when added to cart', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to cart')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this item was last updated')),
                ('cart', models.ForeignKey(help_text='Cart this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(help_text='Product being added to cart', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant (size, color, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='When this item was added to wishlist')),
                ('product', models.ForeignKey(help_text='Product in wishlist', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('variant', models.ForeignKey(blank=True, help_text='Product variant (size, color, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('wishlist', models.ForeignKey(help_text='Wishlist this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.wishlist')),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['wishlist', 'product'], name='cart_wishli_wishlis_074010_idx'), models.Index(fields=['wishlist', 'variant'], name='cart_wishli_wishlis_05c894_idx'), models.Index(fields=['added_at'], name='cart_wishli_added_a_0db258_idx')],
                'unique_together': {('wishlist', 'product', 'variant')},
            },
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'is_active'], name='cart_wishli_user_id_dbeffb_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='cart_wishli_created_6265dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='cart_cartit_cart_id_4bd8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'variant'], name='cart_cartit_cart_id_8609d3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='cart_cartit_added_a_c3b0c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'is_active'], name='cart_cart_user_id_5d777a_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key', 'is_active'], name='cart_cart_session_3c25be_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='cart_cart_expires_8a239f_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='cart_cart_created_981ed1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('session_key', 'is_active'), ('user', 'is_active')},
        ),
    ]
