# Generated by Django 4.2.4 on 2025-09-26 09:39

from django.db import migrations
from django.db.models import Count


def clean_duplicate_carts(apps, schema_editor):
    """
    Clean up duplicate carts for each user, keeping only the most recent one
    """
    Cart = apps.get_model('cart', 'Cart')
    
    # Find users with multiple carts
    users_with_multiple_carts = Cart.objects.values('user').annotate(
        cart_count=Count('id')
    ).filter(cart_count__gt=1, user__isnull=False)
    
    print(f"Found {len(users_with_multiple_carts)} users with multiple carts")
    
    for user_data in users_with_multiple_carts:
        user_id = user_data['user']
        user_carts = Cart.objects.filter(user_id=user_id).order_by('-created_at')
        
        # Keep the most recent cart, delete others
        keep_cart = user_carts.first()
        duplicate_carts = user_carts.exclude(id=keep_cart.id)
        
        print(f"User {user_id}: Keeping cart {keep_cart.id}, deleting {duplicate_carts.count()} duplicates")
        
        # Delete duplicate carts
        duplicate_carts.delete()


def reverse_clean_duplicate_carts(apps, schema_editor):
    """
    Reverse migration - nothing to do
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_duplicate_carts, reverse_clean_duplicate_carts),
    ]
