# Generated by Django 4.2.4 on 2025-09-18 12:16

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', help_text='Invoice status', max_length=20)),
                ('invoice_date', models.DateTimeField(auto_now_add=True, help_text='Date when invoice was created')),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date for payment', null=True)),
                ('company_name', models.CharField(default='Anon Ecommerce', help_text='Company name', max_length=200)),
                ('company_logo', models.URLField(blank=True, help_text='Company logo URL', null=True)),
                ('company_address', models.TextField(default='Dhaka, Bangladesh', help_text='Company address')),
                ('company_phone', models.CharField(default='+8801XXXXXXXXX', help_text='Company phone number', max_length=20)),
                ('company_email', models.EmailField(default='info@anonecommerce.com', help_text='Company email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Order this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
