# Generated by Django 4.2.4 on 2025-09-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'permissions': [('can_create_category', 'Can create category'), ('can_edit_category', 'Can edit category'), ('can_delete_category', 'Can delete category')], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'permissions': [('can_create_subcategory', 'Can create subcategory'), ('can_edit_subcategory', 'Can edit subcategory'), ('can_delete_subcategory', 'Can delete subcategory')], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
