# Generated by Django 4.2.4 on 2025-09-16 06:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productvariant_productimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_per_item',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='compare_at_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='cost_per_item',
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old price (original price before discount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old price (original price before discount)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
