# Generated by Django 4.2.4 on 2025-09-16 06:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_compare_at_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='option1_name',
            field=models.CharField(blank=True, help_text='Option 1 name (e.g., Size)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option2_name',
            field=models.CharField(blank=True, help_text='Option 2 name (e.g., Color)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='option3_name',
            field=models.CharField(blank=True, help_text='Option 3 name (e.g., Material)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('variable', 'Variable')], default='simple', help_text='Product type', max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option1_name',
            field=models.CharField(blank=True, help_text='Option 1 name (e.g., Size)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option1_value',
            field=models.CharField(blank=True, help_text='Option 1 value (e.g., Small)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option2_name',
            field=models.CharField(blank=True, help_text='Option 2 name (e.g., Color)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option2_value',
            field=models.CharField(blank=True, help_text='Option 2 value (e.g., Red)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option3_name',
            field=models.CharField(blank=True, help_text='Option 3 name (e.g., Material)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option3_value',
            field=models.CharField(blank=True, help_text='Option 3 value (e.g., Cotton)', max_length=100, null=True),
        ),
    ]
