# Generated by Django 4.2.4 on 2025-09-16 08:28

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_option1_name_product_option2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Option name (e.g., Size, Color, Material)', max_length=50)),
                ('value', models.CharField(help_text='Option value (e.g., Small, Red, Cotton)', max_length=100)),
                ('position', models.PositiveIntegerField(default=1, help_text='Display position')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_options', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Variant Option',
                'verbose_name_plural': 'Variant Options',
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['variant'], name='products_va_variant_a2102f_idx'), models.Index(fields=['name'], name='products_va_name_720a66_idx')],
                'unique_together': {('variant', 'name', 'value')},
            },
        ),
    ]
