# Generated by Django 4.2.4 on 2025-09-16 12:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_variantoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=255, null=True)),
                ('comment', models.TextField(help_text='Review comment')),
                ('user_name', models.CharField(blank=True, help_text='User name for guest reviews', max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, help_text='User email for guest reviews', max_length=254, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Is this review approved?')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Is this a verified purchase?')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of helpful votes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True, help_text='Is this vote helpful?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='products.productreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Vote',
                'verbose_name_plural': 'Review Votes',
                'indexes': [models.Index(fields=['review'], name='products_re_review__1742c1_idx'), models.Index(fields=['user'], name='products_re_user_id_941832_idx')],
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product'], name='products_pr_product_385307_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user'], name='products_pr_user_id_c2c9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['rating'], name='products_pr_rating_0e31b2_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved'], name='products_pr_is_appr_790eda_idx'),
        ),
    ]
