# Generated by Django 4.2.4 on 2025-09-27 19:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreview_reviewvote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default variant price (cached for performance)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.ForeignKey(blank=True, help_text='Default variant for variable products', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_product', to='products.productvariant'),
        ),
    ]
