# Generated by Django 4.2.4 on 2025-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_and_notifications', '0003_discount_discountusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_image',
            field=models.ImageField(blank=True, help_text='Discount banner image', null=True, upload_to='discounts/images/'),
        ),
        migrations.AddField(
            model_name='discount',
            name='display_type',
            field=models.CharField(choices=[('modal', 'Modal Popup'), ('image', 'Image Banner'), ('both', 'Both Modal and Image')], default='modal', help_text='How to display the discount notification', max_length=10),
        ),
        migrations.AddField(
            model_name='discount',
            name='image_alt_text',
            field=models.CharField(blank=True, help_text='Alt text for discount image', max_length=200),
        ),
        migrations.AddField(
            model_name='discount',
            name='modal_button_text',
            field=models.CharField(default='Shop Now', help_text='Button text in modal', max_length=50),
        ),
        migrations.AddField(
            model_name='discount',
            name='modal_title',
            field=models.CharField(blank=True, help_text='Modal title (if different from name)', max_length=200),
        ),
    ]
