# Generated by Django 4.2.4 on 2025-09-27 19:52

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('chat_and_notifications', '0004_discount_discount_image_discount_display_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='discountusage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_users',
        ),
        migrations.AlterUniqueTogether(
            name='notificationview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notificationview',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='DiscountUsage',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationView',
        ),
    ]
