# Generated by Django 4.2.4 on 2025-09-29 14:15

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chat_and_notifications', '0005_alter_discountusage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact person name', max_length=100)),
                ('email', models.EmailField(help_text='Contact person email', max_length=254)),
                ('subject', models.CharField(help_text='Contact subject', max_length=200)),
                ('message', models.TextField(help_text='Contact message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this contact message has been read')),
                ('is_replied', models.BooleanField(default=False, help_text='Whether this contact message has been replied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
